# Generated by Django 4.2.7 on 2026-04-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_room_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='position',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('C', 'Center'), ('custom', 'Custom')], default='custom', max_length=10),
        ),
    ]
