# Generated by Django 4.2.7 on 2026-04-22 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_room_floor_room_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='position',
        ),
    ]
