# Generated by Django 4.2.7 on 2026-04-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_room_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='bed_type',
            field=models.CharField(choices=[('single', 'Single'), ('double_deck', 'Double Deck'), ('both', 'Both')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='electricity_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_aircon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_fan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_lababo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_ref',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='num_cr',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='water_included',
            field=models.BooleanField(default=False),
        ),
    ]
