# Generated by Django 4.2.7 on 2026-04-22 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_room_area_room_bed_type_room_electricity_included_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.room'),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='room_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
