# Generated by Django 4.2.7 on 2026-04-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_appliance_inclusion_room_dynamic_appliances_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='dynamic_appliances',
        ),
        migrations.RemoveField(
            model_name='room',
            name='has_aircon',
        ),
        migrations.RemoveField(
            model_name='room',
            name='has_fan',
        ),
        migrations.RemoveField(
            model_name='room',
            name='has_ref',
        ),
        migrations.RemoveField(
            model_name='room',
            name='has_tv',
        ),
    ]
