# Generated by Django 4.2.7 on 2026-04-26 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_room_dynamic_appliances_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantprofile',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.room'),
        ),
    ]
