# Generated by Django 4.2.7 on 2026-04-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_tenantprofile_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
