# Generated by Django 4.2.7 on 2026-04-27 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0017_alter_bill_options_remove_bill_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('tenant_created', 'Tenant Created'), ('tenant_updated', 'Tenant Updated'), ('tenant_deleted', 'Tenant Deleted'), ('room_created', 'Room Created'), ('room_updated', 'Room Updated'), ('room_deleted', 'Room Deleted'), ('bill_generated', 'Bill Generated'), ('bill_updated', 'Bill Updated'), ('bill_deleted', 'Bill Deleted'), ('bill_sent', 'Bill Sent'), ('payment_recorded', 'Payment Recorded'), ('payment_deleted', 'Payment Deleted'), ('admin_created', 'Admin Created'), ('admin_updated', 'Admin Updated'), ('admin_deleted', 'Admin Deleted'), ('maintenance_created', 'Maintenance Created'), ('maintenance_updated', 'Maintenance Updated'), ('maintenance_completed', 'Maintenance Completed')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(blank=True, help_text='Model name (e.g., Bill, TenantProfile)', max_length=100)),
                ('object_id', models.IntegerField(blank=True, help_text='ID of the related object', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
