# Generated by Django 4.2.7 on 2026-04-27 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0018_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('tenant_created', 'Tenant Created'), ('tenant_updated', 'Tenant Updated'), ('tenant_deleted', 'Tenant Deleted'), ('room_created', 'Room Created'), ('room_updated', 'Room Updated'), ('room_deleted', 'Room Deleted'), ('bill_generated', 'Bill Generated'), ('bill_updated', 'Bill Updated'), ('bill_deleted', 'Bill Deleted'), ('bill_sent', 'Bill Sent'), ('payment_recorded', 'Payment Recorded'), ('payment_deleted', 'Payment Deleted'), ('admin_created', 'Admin Created'), ('admin_updated', 'Admin Updated'), ('admin_deleted', 'Admin Deleted'), ('maintenance_created', 'Maintenance Created'), ('maintenance_updated', 'Maintenance Updated'), ('maintenance_completed', 'Maintenance Completed'), ('reminder_created', 'Reminder Created'), ('reminder_sent', 'Reminder Sent')], max_length=50),
        ),
        migrations.CreateModel(
            name='TenantReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('reminder_type', models.CharField(choices=[('cleanliness', 'Cleanliness'), ('rules', 'House Rules'), ('payment', 'Payment Reminder'), ('general', 'General')], default='general', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Optional: Schedule for future delivery', null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('read', 'Read')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='accounts.tenantprofile')),
            ],
            options={
                'verbose_name': 'Tenant Reminder',
                'verbose_name_plural': 'Tenant Reminders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
