# Generated by Django 4.2.7 on 2026-05-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_activitylog_idx_activity_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_id',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
