# Generated by Django 4.2.7 on 2026-05-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_payment_receipt_id_payment_receipt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, help_text='URL to redirect when notification is clicked', max_length=500),
        ),
    ]
