# Generated by Django 4.2.7 on 2026-05-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_add_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('payment', 'Payment'), ('billing', 'Billing'), ('maintenance', 'Maintenance'), ('announcement', 'Announcement'), ('system', 'System'), ('reminder', 'Reminder')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='Internal URL path for redirection', max_length=255),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='idx_notification_user_created'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='idx_notification_user_read'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type'], name='idx_notification_type'),
        ),
    ]
