# Generated by Django 4.2.7 on 2026-05-04 12:32

from django.db import migrations, models
from django.core.validators import RegexValidator


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_upgrade_notification_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='phone',
            field=models.CharField(max_length=20, validators=[RegexValidator(regex=r'^[0-9]{10,15}$', message='Phone must contain only digits (10-15 numbers)')]),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='phone',
            field=models.CharField(max_length=20, validators=[RegexValidator(regex=r'^[0-9]{10,15}$', message='Phone must contain only digits (10-15 numbers)')]),
        ),
    ]
