# Generated by Django 4.2.7 on 2026-05-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_add_phone_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
