# Generated by Django 4.2.7 on 2026-05-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_adminprofile_phone_alter_payment_receipt_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('tenant_created', 'Tenant Created'), ('tenant_updated', 'Tenant Updated'), ('tenant_deleted', 'Tenant Deleted'), ('room_created', 'Room Created'), ('room_updated', 'Room Updated'), ('room_deleted', 'Room Deleted'), ('bill_generated', 'Bill Generated'), ('bill_updated', 'Bill Updated'), ('bill_deleted', 'Bill Deleted'), ('bill_sent', 'Bill Sent'), ('payment_recorded', 'Payment Recorded'), ('payment_deleted', 'Payment Deleted'), ('admin_created', 'Admin Created'), ('admin_updated', 'Admin Updated'), ('admin_deleted', 'Admin Deleted'), ('maintenance_created', 'Maintenance Created'), ('maintenance_updated', 'Maintenance Updated'), ('maintenance_completed', 'Maintenance Completed'), ('reminder_created', 'Reminder Created'), ('reminder_sent', 'Reminder Sent'), ('rule_created', 'Rule Created'), ('rule_deleted', 'Rule Deleted')], max_length=50),
        ),
    ]
