# Generated by Django 4.2.7 on 2026-05-07 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_rule_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must contain only digits (10-15 numbers).', regex='^\\d{10,15}$')]),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must contain only digits (10-15 numbers).', regex='^\\d{10,15}$')]),
        ),
    ]
