# Generated by Django 4.2.7 on 2026-05-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_adminprofile_phone_alter_tenantprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('tenant_created', 'Tenant Created'), ('tenant_updated', 'Tenant Updated'), ('tenant_deleted', 'Tenant Deleted'), ('room_created', 'Room Created'), ('room_updated', 'Room Updated'), ('room_deleted', 'Room Deleted'), ('bill_generated', 'Bill Generated'), ('bill_updated', 'Bill Updated'), ('bill_deleted', 'Bill Deleted'), ('bill_sent', 'Bill Sent'), ('payment_recorded', 'Payment Recorded'), ('payment_deleted', 'Payment Deleted'), ('payment_proof_uploaded', 'Payment Proof Uploaded'), ('admin_created', 'Admin Created'), ('admin_updated', 'Admin Updated'), ('admin_deleted', 'Admin Deleted'), ('maintenance_created', 'Maintenance Created'), ('maintenance_updated', 'Maintenance Updated'), ('maintenance_completed', 'Maintenance Completed'), ('reminder_created', 'Reminder Created'), ('reminder_sent', 'Reminder Sent'), ('rule_created', 'Rule Created'), ('rule_deleted', 'Rule Deleted')], max_length=50),
        ),
    ]
