# Generated by Django 4.2.7 on 2026-05-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['-updated_at'], name='accounts_bi_updated_deab06_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['-created_at'], name='accounts_bi_created_5bde53_idx'),
        ),
    ]
