# Generated by Django 4.2.7 on 2026-05-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_bill_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='billing_active',
            field=models.BooleanField(default=False, help_text='Whether automatic billing is active'),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='billing_start_date',
            field=models.DateField(blank=True, help_text='Date when billing cycle starts', null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='first_login_at',
            field=models.DateTimeField(blank=True, help_text='First time tenant logged in', null=True),
        ),
    ]
