# Generated by Django 4.2.7 on 2026-05-08 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_tenantprofile_billing_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Date when billing cycle starts')),
                ('next_billing_date', models.DateField(help_text='Date of next billing generation')),
                ('billing_day', models.PositiveIntegerField(default=1, help_text='Day of month for billing (1-31)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether billing cycle is active')),
                ('grace_period_days', models.PositiveIntegerField(default=5, help_text='Grace period for due dates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_cycle', to='accounts.tenantprofile')),
            ],
            options={
                'ordering': ['next_billing_date'],
                'indexes': [models.Index(fields=['next_billing_date'], name='accounts_bi_next_bi_dab392_idx'), models.Index(fields=['is_active'], name='accounts_bi_is_acti_e687cf_idx')],
            },
        ),
    ]
