# Generated by Django 4.2.7 on 2026-05-08 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_billingcycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingcycle',
            name='tenant',
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='bill',
            name='accounts_bi_updated_deab06_idx',
        ),
        migrations.RemoveIndex(
            model_name='bill',
            name='accounts_bi_created_5bde53_idx',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='billing_active',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='billing_start_date',
        ),
        migrations.RemoveField(
            model_name='tenantprofile',
            name='first_login_at',
        ),
        migrations.DeleteModel(
            name='BillingCycle',
        ),
    ]
