# Generated by Django 4.2.7 on 2026-05-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_room_media_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('payment', 'Payment'), ('billing', 'Billing'), ('maintenance', 'Maintenance'), ('announcement', 'Announcement'), ('system', 'System'), ('reminder', 'Reminder'), ('payment_proof', 'Payment Proof')], max_length=50, null=True),
        ),
    ]
