# Generated by Django 4.2.7 on 2026-05-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_add_notification_index'),
    ]

    operations = [
    ]
