from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


CANVAS_SIZE = (900, 1200)
PADDING = 70


def _load_font(size, bold=False):
    font_names = [
        "arialbd.ttf" if bold else "arial.ttf",
        "DejaVuSans-Bold.ttf" if bold else "DejaVuSans.ttf",
    ]
    for font_name in font_names:
        try:
            return ImageFont.truetype(font_name, size=size)
        except OSError:
            continue
    return ImageFont.load_default()


def _draw_label_value(draw, y, label, value, label_font, value_font, ink):
    draw.text((PADDING, y), label.upper(), fill="#6b7280", font=label_font)
    draw.text((PADDING, y + 28), str(value or "-"), fill=ink, font=value_font)
    return y + 92


def render_receipt_png(data, file_path):
    """
    Render a clean PNG receipt using Pillow.

    The caller is responsible for passing normalized receipt data and choosing
    the storage location.
    """
    output_path = Path(file_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    image = Image.new("RGB", CANVAS_SIZE, "white")
    draw = ImageDraw.Draw(image)

    title_font = _load_font(46, bold=True)
    subtitle_font = _load_font(24, bold=True)
    label_font = _load_font(18, bold=True)
    value_font = _load_font(28)
    small_font = _load_font(18)

    ink = "#111827"
    accent = "#2563eb"
    muted = "#6b7280"

    draw.rectangle((0, 0, CANVAS_SIZE[0], 14), fill=accent)
    draw.text((PADDING, 70), data.get("system_name", "RENTS Boarding House"), fill=ink, font=title_font)
    draw.text((PADDING, 126), "Official Payment Receipt", fill=muted, font=subtitle_font)

    receipt_id = data.get("receipt_id", "-")
    draw.rounded_rectangle((PADDING, 190, CANVAS_SIZE[0] - PADDING, 270), radius=12, outline="#d1d5db", width=2)
    draw.text((PADDING + 28, 210), "Receipt ID", fill=muted, font=small_font)
    draw.text((PADDING + 28, 235), receipt_id, fill=accent, font=subtitle_font)

    draw.line((PADDING, 320, CANVAS_SIZE[0] - PADDING, 320), fill="#e5e7eb", width=3)

    y = 370
    fields = [
        ("Tenant Name", data.get("tenant_name")),
        ("Room Number", data.get("room")),
        ("Payment Date", data.get("date")),
        ("Billing Period", data.get("billing_period")),
        ("Payment Type", data.get("payment_method")),
        ("Status", data.get("status", "Paid")),
    ]
    for label, value in fields:
        y = _draw_label_value(draw, y, label, value, label_font, value_font, ink)

    amount_text = data.get("amount_display") or f"PHP {data.get('amount', 0):,.2f}"
    draw.rounded_rectangle((PADDING, y + 8, CANVAS_SIZE[0] - PADDING, y + 128), radius=14, fill="#f0fdf4")
    draw.text((PADDING + 28, y + 30), "AMOUNT PAID", fill="#166534", font=label_font)
    draw.text((PADDING + 28, y + 62), amount_text, fill="#15803d", font=title_font)

    footer_y = CANVAS_SIZE[1] - 120
    draw.line((PADDING, footer_y, CANVAS_SIZE[0] - PADDING, footer_y), fill="#e5e7eb", width=2)
    draw.text((PADDING, footer_y + 28), "Generated by RENTS System", fill=muted, font=small_font)

    image.save(output_path, format="PNG", optimize=True)
    return str(output_path)
