# Generated by Django 4.2.7 on 2026-05-12 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Unique code for this notification type', max_length=60, unique=True)),
                ('label', models.CharField(help_text='Human-readable name for this notification type', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of when this notification type is used')),
                ('icon', models.CharField(blank=True, help_text="CSS icon class or name (e.g., 'bi-info-circle')", max_length=50)),
                ('color', models.CharField(blank=True, help_text="Bootstrap color class (e.g., 'success')", max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this notification type can be used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification Type',
                'verbose_name_plural': 'Notification Types',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_channel', models.CharField(choices=[('in_app', 'In-App Only'), ('email', 'Email'), ('sms', 'SMS'), ('all', 'All Channels'), ('none', 'Disabled')], default='in_app', max_length=20)),
                ('type_overrides', models.JSONField(blank=True, default=dict, help_text='Per-type channel overrides for this user')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start time when user should not receive notifications', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End time when user should not receive notifications', null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Notification Preference',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', max_length=10)),
                ('title_template', models.CharField(help_text="Use {{ variable_name }} for substitution. E.g., 'New message from {{ sender }}'", max_length=255)),
                ('body_template', models.TextField(help_text='Supports {{ variable_name }} substitution.')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default template for this notification type')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='notifications.notificationtype')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'unique_together': {('notification_type', 'language')},
            },
        ),
    ]
